blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/behify/persian-calendar-excel/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/behify/persian-calendar-excel/blob/main/docs/API.md
    about: Read the API documentation and usage examples