name: Test Persian Calendar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: List repository contents
      run: |
        echo "Repository structure:"
        find . -type f -name "*.md" -o -name "*.bas" -o -name "*.yml" -o -name "*.json" | head -20
    
    - name: Check basic files
      run: |
        echo "Checking for basic files..."
        
        if [ -f "README.md" ]; then
          echo "✓ README.md found"
        else
          echo "✗ README.md missing"
        fi
        
        if [ -f "LICENSE" ]; then
          echo "✓ LICENSE found"
        else
          echo "✗ LICENSE missing"
        fi
        
        if [ -d "src" ]; then
          echo "✓ src directory found"
          echo "Files in src/:"
          ls -la src/ || echo "src directory is empty"
        else
          echo "○ src directory not found (this is normal for initial setup)"
        fi
    
    - name: Validate README content
      run: |
        if [ -f "README.md" ]; then
          echo "README.md content preview:"
          head -10 README.md
          
          if grep -q "Persian Calendar" README.md; then
            echo "✓ README contains Persian Calendar reference"
          else
            echo "⚠ README missing Persian Calendar reference"
          fi
        fi